name: starship-devnet
version: 0.2.14

chains:
  - id: hyperweb
    name: custom
    numValidators: 1
    image: ghcr.io/cosmology-tech/jsd:0.1.1
    home: /root/.jsd
    binary: jsdd
    prefix: hyper
    denom: uhyper
    coins: 100000000000000uhyper,100000000000000uweb,100000000000000ATOM,100000000000000USDC
    hdPath: m/44'/118'/0'/0/0
    coinType: 118
    repo: https://github.com/cosmology-tech/jsd
    ports:
      rest: 1313
      rpc: 26653
      faucet: 8003
    faucet:
      enabled: true
      type: starship

registry:
  enabled: true
  ports:
    rest: 8081

explorer:
  enabled: false
  ports:
    rest: 8080

images:
  imagePullPolicy: Always
